PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Categories (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Name TEXT NOT NULL,
    Description TEXT NULL
);

CREATE TABLE IF NOT EXISTS Customers (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Name TEXT NOT NULL,
    Phone TEXT NULL,
    Address TEXT NULL,
    Email TEXT NULL,
    LastOrderDate TEXT NULL
);

CREATE TABLE IF NOT EXISTS InventoryItems (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Name TEXT NOT NULL,
    Quantity NUMERIC NOT NULL,
    Unit TEXT NOT NULL,
    MinQuantity NUMERIC NOT NULL,
    UnitCost NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS Salgados (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Nome TEXT NOT NULL,
    Preco NUMERIC NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Username TEXT NOT NULL,
    PasswordHash TEXT NOT NULL,
    FullName TEXT NOT NULL,
    Role INTEGER NOT NULL,
    IsActive INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Name TEXT NOT NULL,
    Description TEXT NULL,
    Price NUMERIC NOT NULL,
    CategoryId INTEGER NOT NULL,
    StockQuantity INTEGER NOT NULL DEFAULT 0,
    TrackStock INTEGER NOT NULL DEFAULT 0,
    ImageUrl TEXT NULL,
    FOREIGN KEY (CategoryId) REFERENCES Categories (Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Orders (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OrderDate TEXT NOT NULL,
    Total NUMERIC NOT NULL,
    OrderType INTEGER NOT NULL,
    Status INTEGER NOT NULL,
    TableNumber INTEGER NULL,
    CustomerId INTEGER NULL,
    Notes TEXT NULL,
    FOREIGN KEY (CustomerId) REFERENCES Customers (Id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS OrderItems (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OrderId INTEGER NOT NULL,
    ProductId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL,
    UnitPrice NUMERIC NOT NULL,
    Notes TEXT NULL,
    FOREIGN KEY (OrderId) REFERENCES Orders (Id) ON DELETE CASCADE,
    FOREIGN KEY (ProductId) REFERENCES Products (Id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS FinancialTransactions (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    DataCriacao TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TransactionDate TEXT NOT NULL,
    Amount NUMERIC NOT NULL,
    Type INTEGER NOT NULL,
    Description TEXT NOT NULL,
    OrderId INTEGER NULL,
    Category TEXT NULL,
    FOREIGN KEY (OrderId) REFERENCES Orders (Id) ON DELETE SET NULL
);
